/**
 * @file sr_port_stm32.c
 * @brief STM32 implementation of sr_port.h (template — fill in your pins).
 *
 * To use this file on STM32CubeIDE:
 *   1. Configure DATA, SHIFT_CLK, LATCH, OE_N as GPIO_Output in CubeMX.
 *   2. Adjust the #defines below to match the port/pin you chose.
 *   3. Add this file and shift_register.c to the Src/ folder.
 *   4. Add the include/ folder to the include path.
 *   5. Do NOT compile sr_port_esp32.c — only one port file per build.
 */

#include "sr_port.h"
#include "main.h"   /* pulls in HAL + the GPIOx_Pin macros from CubeMX */

/* --- Edit these to match your CubeMX configuration --- */
#define SR_DATA_PORT        GPIOA
#define SR_DATA_PIN         GPIO_PIN_0
#define SR_SHIFT_CLK_PORT   GPIOA
#define SR_SHIFT_CLK_PIN    GPIO_PIN_1
#define SR_LATCH_PORT       GPIOA
#define SR_LATCH_PIN        GPIO_PIN_2
#define SR_OE_N_PORT        GPIOA
#define SR_OE_N_PIN         GPIO_PIN_3
/* ------------------------------------------------------ */

int sr_port_init(void)
{
    /* GPIOs are already configured by MX_GPIO_Init() generated by CubeMX,
     * so there is nothing left to do here. Return 0 for success. */
    return 0;
}

void sr_port_write(sr_line_t line, bool level)
{
    const GPIO_PinState s = level ? GPIO_PIN_SET : GPIO_PIN_RESET;

    switch (line) {
        case SR_LINE_DATA:      HAL_GPIO_WritePin(SR_DATA_PORT,      SR_DATA_PIN,      s); break;
        case SR_LINE_SHIFT_CLK: HAL_GPIO_WritePin(SR_SHIFT_CLK_PORT, SR_SHIFT_CLK_PIN, s); break;
        case SR_LINE_LATCH:     HAL_GPIO_WritePin(SR_LATCH_PORT,     SR_LATCH_PIN,     s); break;
        case SR_LINE_OE_N:      HAL_GPIO_WritePin(SR_OE_N_PORT,      SR_OE_N_PIN,      s); break;
        default: break;
    }
}

void sr_port_delay_short(void)
{
    /* A handful of NOPs is plenty at typical STM32 core clocks. */
    for (volatile int i = 0; i < 8; ++i) { __asm__("nop"); }
}
